android.useAndroidX=true
org.gradle.jvmargs=-Xmx4096m
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.injected.androidTest.leaveApksInstalledAfterRun=true
testify_version=6.0.0
# Required for Kotlin sources in an Android library's `src/testFixtures` source set.
# Used by :PaparazziSampleLibrary to share PaparazziTestRule with :PaparazziSample's unit tests.
android.experimental.enableTestFixturesKotlinSupport=true
